---

- name: Update packages
  apt: update_cache=yes

- name: Install PHP and common package
  apt: name={{ item }} state=present
  with_items: php_packages
  tags:
    - php
    - php-package
  notify:
    - restart apache

- name: Modified PHP configuration file
  template: src=php.ini.j2 dest=/etc/php5/apache2/php.ini
  tags:
    - php
    - php-config
  notify:
    - restart apache
